name: fmagus
description: Dart package to automate the boring work, like creating assets, folder structures, importing packages etc for Flutter via CLI.
version: 1.2.3
homepage: https://github.com/tuliogd/fmagus

environment:
  sdk: 3.7.0

dependencies:
  args: ^2.6.0
  process_run: ^1.2.3
  image: ^4.5.3

dev_dependencies:
  lints: ^5.1.1
