name: fmagus
description: Dart package to automate the boring work, like creating assets, folder structures, importing packages etc for Flutter via CLI.
version: 1.0.4
homepage: https://github.com/tuliogd/fmagus

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  args: ^2.4.0
  process_run: ^0.12.5+2
  image: ^4.0.15

dev_dependencies:
  lints: ^2.0.1
