name: fmagus
description: Dart package to automate the boring work, like creating assets, folder structures, importing packages etc for Flutter via CLI.
version: 1.1.2
homepage: https://github.com/tuliogd/fmagus

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  args: ^2.4.2
  process_run: ^0.13.2
  image: ^4.1.3

dev_dependencies:
  lints: ^3.0.0
