name: fmagus
description: Dart package to automate the boring work, like creating assets, folder structures, importing packages etc for Flutter via CLI.
version: 1.1.2
homepage: https://github.com/tuliogd/fmagus

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  args: ^2.4.2
  process_run: ^0.13.1
  image: ^4.0.17

dev_dependencies:
  lints: ^2.1.1
