name: fmagus
description: Dart package to automate the boring work, like creating assets, folder structures, importing packages etc for Flutter via CLI.
version: 1.2.4
homepage: https://github.com/tuliogd/fmagus

environment:
  sdk: 3.7.2

dependencies:
  args: ^2.7.0
  process_run: ^1.2.4
  image: ^4.5.3

dev_dependencies:
  lints: ^5.1.1
